# plot species' density distributions in trait space (in 1D)
# Input:
# - snap: data generated by "organize_results()" in "solve_eqs.R", restricted
#         to a single point in time (i.e., a snapshot of the dynamics)
# - limits: vector with three entries: lower limit of trait axis, upper limit
#           of trait axis, and upper limit of y-axis. If this last entry is set
#           to NA, the y-axis will be scaled automatically
# - res: resolution of the trait axis, the number of grid points it gets
#        subdivided into to generate the plot
# - b: a function, giving the intrinsic growth rate as a function of phenotype z
# Output:
# - a plot of the species' density distributions
plot_snapshot <- function(snap, limits=c(-1, 1, NA), res=1001, b) {
  species <- unique(snap$species)
  xlimits <- range(c(snap$m-4*snap$s, snap$m+4*snap$s))
  if (is.na(limits[1])) limits[1] <- xlimits[1]
  if (is.na(limits[2])) limits[2] <- xlimits[2]
  traitaxis <- seq(limits[1], limits[2], l=res) # sampling the trait axis
  traits <- expand_grid(species=species, trait=traitaxis) # trait tab
  traits["density"] <- 0 # add column for population densities
  for (i in 1:S) {
    n <- filter(snap, species==i)$n
    m <- filter(snap, species==i)$m
    P <- filter(snap, species==i)$G
    P <- P + filter(snap, species==i)$E
    traits$density[(traits$species==i)] <- n *
      dnorm(traits$trait[(traits$species==i)], m, sqrt(P))
    traits$density[(traits$species==i)][
      traits$density[(traits$species==i)]<n*0.001/sqrt(P)] <- NA
  }
  traits$density[traits$density<1e-6] <- NA
  landscape <- data.frame(trait=traitaxis, r=0)
  landscape$r <- b(landscape$trait)
  landscape$r[landscape$r<0] <- NA
  if (is.na(limits[3])) limits[3] <- max(traits$density,na.rm=TRUE)
  landscape$r <- landscape$r * limits[3]
  ggplot(traits) +
    geom_line(aes(x=trait, y=density, group=as_factor(species)),
              colour="#0072B2", na.rm=TRUE) +
    geom_ribbon(aes(x=trait, ymin=0, ymax=density, group=as_factor(species)),
                fill="#0072B2", alpha=0.15) +
    geom_line(data=landscape, aes(x=trait, y=r), linetype="dashed",
              colour="#CC79A7", alpha=0.8, na.rm=TRUE) +
    scale_x_continuous(name="trait value", limits=c(limits[1], limits[2])) +
    scale_y_continuous(name="density", limits=c(0, limits[3]),
                       sec.axis=sec_axis(~./limits[3],
                                         name="intrinsic growth rate",
                                         breaks=c(0, 1))) +
    theme_bw() +
    theme(legend.position="none", panel.grid=element_blank())
}
